### ISSUE TITLE
NOT AN ISSUE but just a question about MAUI

### ISSUE THREAD

**Issue by developer9969** [dansiegel/Prism.Maui#13]
Hey Daniel,
We love prism , can you give us a clue when we can have a Prism.Maui???

We want to move to MAUI , but we cannot even start as we are all in with Prism!!

Maui as you know will go live in a month , any plans? clues? anything?
Very grateful

thanks

**Comment by dansiegel** [comment]
@developer9969 apologies for the delayed response I have been on a much needed and overdue vacation the last few weeks.

I am looking at getting this out as soon as I can. The work the MAUI team did with their implementation of Multiple Window support while keeping legacy App.MainPage supported has created some real chicken or egg issues for me to work around in the initialization. @jBijsterboschNL has been doing some work which I will be reviewing this week to see if we can hopefully get a new preview out.

**Comment by dansiegel** [comment]
Updated versions of Prism.Maui are available for Sponsors in the [Sponsor Connect](https://sponsorconnect.dev) NuGet feed. We will be making this publicly available soon.
