### ISSUE TITLE
Extension method is missing from NuGet package 

### ISSUE THREAD

**Issue by husseinmohkhalil** [dansiegel/Prism.Maui#25]
I have only created a new MAUI application and installed both Prism.Maui and Prism.DryIoc.Maui NuGet packages
I am gettinge an error 

`'MauiAppBuilder' does not contain a definition for 'UsePrismApp' and no accessible extension method 'UsePrismApp' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)
`
But I am sure I have added all the references. I have checked the code sample, and it is referencing the project directly. 
Any suggestions please?

**Comment by dansiegel** [comment]
I'm closing this as `you` haven't really given me much to go off of here... I don't know which version of the package you're using, nor do I have a sample project that I can pull up to begin to tell you. It sounds to me like you don't have the Prism namespace.... if you have implicit namespaces it should come in automatically.

**Comment by husseinmohkhalil** [comment]
Sorry for not giving all the needed info
I am using 
Prism.DryIoc.Maui 8.1.27-alpha
Prism.Maui 8.1.27-alpha

I have just created a new MAUI project, added the two NuGets above and then changed     `.UseMauiApp<App>();`  to `.UsePrismApp<App>();`

From my understanding, the extension method called `UsePrismApp<T>` is in static class `PrismAppExtensions`. I have checked, and I am not able to find the class anywhere.

Am I missing another NuGet?

```
namespace PrisumTest;
using Prism;
using Prism.Ioc;
using Prism.Modularity;
using Prism.Navigation;
using Prism.DryIoc;

public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UsePrismApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

		return builder.Build();
	}
}
```

**Comment by dansiegel** [comment]
There is a base extension method:
```cs
builder.UsePrismApp<App>(containerExtension);
```

That is in Prism.Maui... Prism.DryIoc.Maui has the PrismAppExtensions with the extension method `UsePrismApp<App>()`. You ONLY need to add the nuget reference for Prism.DryIoc.Maui for your App Head / Single Project... you'll notice that the sample app has a Prism Module. That project only needs to reference Prism.Maui

**Comment by Advertiqa** [comment]
For future reference, UsePrismApp is dropped with #101

**Comment by azeemchaudhrry** [comment]
For future reference, UsePrismApp is dropped with #101
