### ISSUE TITLE
Possible typo in Prism.Ioc.NavigationRegistrationExtensions ?

### ISSUE THREAD

**Issue by zleao** [dansiegel/Prism.Maui#6]
Am I seing it wrong, or shouldn't this call be: `container.RegisterForNavigation`?

https://github.com/dansiegel/Prism.Maui/blob/preview8/src/Prism.Maui/Ioc/NavigationRegistrationExtensions.cs#:~:text=container.Register(typeof(TView)%2C%20typeof(TViewModel)%2C%20name)%3B

**Comment by UweReisewitz** [comment]
I'm using branch preview9 with VS 2022 Preview 17.1 Preview 5.

After changing the line 14 above the exception "[DryIoc.ContainerException Error.RegisteringImplementationNotAssignableToServiceType](https://github.com/dansiegel/Prism.Maui/issues/9#)
#9 is gone

**Comment by dansiegel** [comment]
@UweReisewitz the branch is currently out of date there are several issues that need to be resolved and I have not had the time to address as the Maui team has implemented scoping around the window and changed the entry point that we need to work against. This complicates things a bit and is an API that is likely still going to change even after I get it working again

**Comment by UweReisewitz** [comment]
@dansiegel is there any way I could help? I'm a long time developer but I have to learn a lot regarding the internal structure of Prism and I'm no GitHub expert. I definitely don't want to cause you more work but if there are things I could do, please let me know.
It probably doesn't make much sense to do anything for the next 10 days or so until Preview 13 comes out but after that...
I know it's frustrating to fix something that won't last until the next preview/version but hey, hasn't Xamarin been this way all the time (sorry, couldn't resist :-) )?

**Comment by UweReisewitz** [comment]
Please excuse my dumb question: How do I contact you on Discord?

**Comment by dansiegel** [comment]
You can DM me at dansiegel#5368

**Comment by jBijsterboschNL** [comment]
This has been 'fixed' in #15
