### ISSUE TITLE
Unhandled managed exception: Unable to resolve service for type 'Prism.Ioc.IContainerExtension' on Mac

### ISSUE THREAD

**Issue by quanvm97** [dansiegel/Prism.Maui#8]
### I just tried to install the package, but can not run the app. Help me fix this issue.

**

IDE: Visual Studio 2022 Preview 2 for Mac
.NET MAUI v0.9.0.0
.NET SDK - Workloads (6.0.100-rc.2.21505.57) 
  ```
✔ android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 
31.0.101-preview.9.16) installed.
  ✔ ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.101-preview.9.31) 
installed.
  ✔ maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 
15.0.101-preview.9.31) installed.
  ✔ tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.101-preview.9.31) 
installed.
  ✔ macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.101-preview.9.31) 
installed.
  ✔ maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.101-preview.9.1843) 
installed.
  ✔ wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 
6.0.0-rc.2.21480.5) installed.
  ✔ microsoft-net-sdk-emscripten 
(microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-rc.2.21474.1) 
installed.

```

The log: 

> Unhandled managed exception: Unable to resolve service for type 'Prism.Ioc.IContainerExtension' while attempting to activate 'TestMaui.App'. (System.InvalidOperationException)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type , CallSiteChain , ParameterInfo[] , Boolean )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache , Type , Type , CallSiteChain )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor , Type , CallSiteChain , Int32 )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type , CallSiteChain )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type , CallSiteChain )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type , CallSiteChain )
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
>    at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func`2 )
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider )
>    at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
> --- End of stack trace from previous location ---
>    at UIKit.UIApplication.Main(String[] , Type , Type )
>    at TestMaui.Program.Main(String[] args) .../Platforms/iOS/Program.cs:line 15

**Comment by moov123** [comment]
Hi,
I am also facing the same issue.Any possible solution?

**Comment by dansiegel** [comment]
On account of time not permitting me to get an update. If someone would like to volunteer to get the preview 9 branch updated to the latest release and submit a PR I'm more than happy to merge the PR and get a new release out

**Comment by dansiegel** [comment]
We will be looking more seriously at bug reports once the new preview is out if they still exist.
