### ISSUE TITLE
Regsitering Page and ViewModel gives DryIoc.ContainerException Error.RegisteringImplementationNotAssignableToServiceType

### ISSUE THREAD

**Issue by UweReisewitz** [dansiegel/Prism.Maui#9]
I routinely register Page and ViewModel explicitly in my code (please see attached project).
``
containerRegistry.RegisterForNavigation<ShoppingItemsPage, ShoppingItemsViewModel>();
``

Register failes with the following error:
DryIoc.ContainerException: 
Error.RegisteringImplementationNotAssignableToServiceType;
Registering implementation type ShoppingListMaui.ViewModels.ShoppingItemsViewModel is not assignable to service type ShoppingListMaui.Views.ShoppingItemsPage.

When using only the Page:
``
containerRegistry.RegisterForNavigation<ShoppingItemsPage>();
``
the registration succeeds but the Navigation fails in PageNaviagtionService.GetPageFromWindow() with the 
Sytem.InvalidOperationException "No page was set on the window."
Unfortunately this Function then silently returns null which causes that app to show no window and just hang around...:

[PrismMauiIssueNavigation.zip](https://github.com/dansiegel/Prism.Maui/files/7376477/PrismMauiIssueNavigation.zip)

**Comment by dansiegel** [comment]
Thank you for the reminder that there was an artifact on the Unit Tests from the older versions of Maui. The appropriate thing to do however is to remove the NuGet reference entirely and use the Maui workload.

**Comment by UweReisewitz** [comment]
I'm still learning. 
```
      <UseMaui>true</UseMaui>
```
was missing. I currently try to figure out what to do next to get the tests running..

**Comment by dansiegel** [comment]
Please see the Preview 9 branch which has these fixes

**Comment by UweReisewitz** [comment]
The problem  is still present in Preview9 (at least on my machine). Just modify line 25 of MauiProgram.cs as follows:
Original:
`containerRegistry.RegisterForNavigation<MainPage>();`
to
`containerRegistry.RegisterForNavigation<MainPage, MainPageViewModel>();`
and add
`using PrismMauiDemo.ViewModels;`
at the top.
With this change it happens in the PrismDemo App as well.

**Comment by dansiegel** [comment]
We will be looking more seriously at bug reports once the new preview is out if they still exist.
